apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: kiada
  name: kiada
spec:
  containers:
  - image: luksa/kiada:0.5
    name: kiada
    ports:
    - containerPort: 8080
    env:
    - name: QUOTE_URL
      value: http://quote/quote
    - name: QUIZ_URL
      value: http://quiz
    - name: POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
#     resources: {}
#   dnsPolicy: ClusterFirst
#   restartPolicy: Always
# status: {}